### PR TITLE
Fix broken build: add dep libzookeeper-mt-dev and fix pip breakage

### PR DESCRIPTION
**Pull request by analogue**
Fixes broken build https://jenkins-jerry.yelpcorp.com/job/nerve-tools/

### CODE REVIEW

**Comment by jvperrin** [comment]
(not sure what's going on with the pypy test)

**Comment by jvperrin** [comment]
Whoops, I meant mypy instead

**Comment by solarkennedy** [comment]
This may fix is in the short term, but it indicates we are not using pip-custom-platform inside, which can lead to not using wheels, which could lead to significant slowdowns (this caused a DAR for paasta).

Can you confirm if you have read `[Audience: debian package owners] How to fix failing dh-virtualenv package builds` ?

I think a better long term solution would be to pin the version of pip (instead of installing the latest version using easy_install) to get a more reproducible build.

**Comment by analogue** [comment]
> This may fix is in the short term, but it indicates we are not using pip-custom-platform inside, which can lead to not using wheels, which could lead to significant slowdowns (this caused a DAR for paasta).
> 
> Can you confirm if you have read `[Audience: debian package owners] How to fix failing dh-virtualenv package builds` ?
> 
> I think a better long term solution would be to pin the version of pip (instead of installing the latest version using easy_install) to get a more reproducible build.

Am I missing something?  

```
spatel@dev57-uswest1adevc:~/git/analogue/nerve-tools (fix_build) $ git grep pip-custom-platform
src/debian/rules:       --pip-tool pip-custom-platform
src/requirements-bootstrap.txt:pip-custom-platform==0.5.0
```
```
spatel@dev57-uswest1adevc:~/git/analogue/nerve-tools (fix_build) $ git grep "pip==" | grep requirements
src/requirements-bootstrap.txt:pip==9.0.3

```
These changes are included in the PR based on https://yelpwiki.yelpcorp.com/display/CORESERV/How+to+modernize+dh-virtualenv+setups

I couldn't find `[Audience: debian package owners] How to fix failing dh-virtualenv package builds` internally or externally.

**Comment by jvperrin** [comment]
So it looks like `pip-custom-platform` is used when actually building the package (by `debian/rules`), however it's not used within the dockerfile when building that, so that's where the tests fail. Maybe those should install using the pinned versions in `requirements-bootstrap.txt` too and then use `pip-custom-platform`?

One difficulty here is that the tests for the PR are run on travis, which doesn't have access to our internal pypi for wheels, and the internal builds should be able to access and make use of the wheels, but they don't appear to be using them properly. Maybe https://github.com/Yelp/nerve-tools/blob/10dac347f340e3843ca02aeda7ce42a0fae942a7/src/debian/rules#L23 isn't working properly?

**Comment by analogue** [comment]
As much as I'd like to fix things for the longer term right now, I've spent a bunch of time just getting the build working itself which is blocking adding a new envoy related feature (CORESERV-9246). 

Would you mind ticketing up the longer term issue? I'd offer to, but I can't say that I understand it as well folks more familiar with this package.

I'd like to get this merged so that the internal build can be verified before continuing on feature development.

**Comment by solarkennedy** [comment]
I'm ok approving a short term fix as long as we are reasonably confident that this won't cause a DAR. I don't feel comfortable approving this change blindly, knowing that we had to revert the analogous change for paasta.

Not using p-c-p on paasta for the dh-virtualenv build caused it to do a ton more IO, so much that it expended ebs burst quotas, etc. configure-nerve could also do that, given how frequently it is called.

Can you build the package on this branch and test out a performance comparison on your devbox? At least for me on dev53-uswest1adevc (not a very scientific comparison):
```
sudo strace -e open configure_nerve 2>&1 | grep 'open(' | wc
   2272    9101  307071
sudo time configure_nerve
1.10user 0.12system 0:01.25elapsed 97%CPU (0avgtext+0avgdata 75312maxresident)k
```

**Comment by analogue** [comment]
@solarkennedy [Requested comparison on dev57](https://fluffy.yelpcorp.com/i/jH2JTBWblC8mld1DNt1wGxsvB9F2q89x.html#L1,L4-7,L21-22,L24,L26,L33-36,L50-51)

**Comment by solarkennedy** [comment]
It looks like it increases the runtime by 30%?

I guess I'm ok fixing the build in the short term and ticketing fixing this to use wheels properly in the long term.

**Pull request merged**
